// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdB1UDrr_gsfypCDJhBk4BJAe3Cew7PkQ',
    appId: '1:616198427949:web:05135a295f2b1d81a92fa4',
    messagingSenderId: '616198427949',
    projectId: 'gomaa-chat-app',
    authDomain: 'gomaa-chat-app.firebaseapp.com',
    storageBucket: 'gomaa-chat-app.appspot.com',
    measurementId: 'G-19YE91MZNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW2f1h34QPqFdYsMhFWwuI-vy__q6hTlg',
    appId: '1:616198427949:android:7868f9942c3c3743a92fa4',
    messagingSenderId: '616198427949',
    projectId: 'gomaa-chat-app',
    storageBucket: 'gomaa-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqxpYwKKLh9kIuMABI0tkIgDNKGtQXhw',
    appId: '1:616198427949:ios:760f41d735a8deb4a92fa4',
    messagingSenderId: '616198427949',
    projectId: 'gomaa-chat-app',
    storageBucket: 'gomaa-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqxpYwKKLh9kIuMABI0tkIgDNKGtQXhw',
    appId: '1:616198427949:ios:c556f6ceafb1d4a1a92fa4',
    messagingSenderId: '616198427949',
    projectId: 'gomaa-chat-app',
    storageBucket: 'gomaa-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
